apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: dummy
spec:
  project: default
  source:
    repoURL: https://github.com/aqsa286/ArgoCD_Private.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowPostSync: true  # Allow synchronization immediately after changes are applied
    syncOptions:
      - ApplyOnly=true  # Apply changes immediately without waiting for a refresh interval
