apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-name
  namespace: test
spec:
  source:
    repoURL: https://github.com/Tap-Payments/devstack.git
    targetRevision: main
    path: k8s/deployments/app-name
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-name
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
