apiVersion: apps/v1
kind: Deployment
metadata:
      name: aqsa
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 736116236436.dkr.ecr.us-east-1.amazonaws.com/private-argocd:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
      name: aqsa
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
